[FEAT] Change release behavior (#44)
* Add new release workflow with version bumping and automated checks

* For testing purposes rename back to old name

* Change deprecated set-output

* Fix checkout step to ensure correct ref is used

* add git status for bug fixing

* Add fetch-tags option to checkout step in manual release workflow

* Set fetch depth for checkout

* Test changes for release workflow

* Add to workflow_dispatch automatic version selection

* Improved logging

* Use error logging

* exit 1 on error

* Fix comparison of auto

* Edit manual release

* Fetch tags

* Update Continuous Deployment to Continuous Delivery

* Test changes in /src (#36)

* Test changes in /src

* Continuous Integration on default branch

* Change Continuous Integration default branch condition

* Continuous Integration only on push

* Remove If

* Test changes to /src (#37)

* Bring back pull request for Continuos Integration

* Continuous Integration change triggers

* Debug message

* Test changes to /src (#38)

* Change readout labels method for Continuous Delivery

* Add permission contents write to Continuous Delivery

* Test changes to /src (#41)

* Try reduced permissions on Continuous Integration

* Implement remove release type tags

* Test changes to /src (#42)

* Test changes to /src

* Make first release automated possible

* Apply version 1.0.0

* Improve release

* Test changes to /src (#43)

* Apply version 1.0.1

* Use Env Var to pass files to release

* Apply version 1.0.1

* Fix checking for local tag

* Fix Skipping if no changes

* Allow forced release

* Force not allowed with type auto

* exit 1 on force release with auto

* exit 1 on manual release with no changes

* remove exit 0

* Apply version 1.1.0

* reactivated on master Continuous Delivery

* Start of beta releases

* Fix force release in case of schedule

* Change cron for testing

* Revert "Change cron for testing"

This reverts commit 87e808ac9f131f1a10a5cacdc04a84219642dfdc.

* Update eslint.config.mjs

* Update git configuration to GitHub Actions bot

* Fix format + typos

* Add Sample command and integrate command registration

* Fix missing package-lock update of version-change.mjs

* Fix condition for removing release type tags in release workflow

* Disable automatic schedule

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,18 +1,17 @@
-name: Continuous Deployment
+name: Continuous Delivery
+
 on:
   pull_request:
     types:
       - closed
     branches: 
       - master  
-  workflow_dispatch:
 
 jobs:
   release:
     runs-on: ubuntu-latest
     if: github.event.pull_request.merged == true
     permissions: 
-        pull-requests: write
         contents: write
 
     steps: 
@@ -20,55 +19,32 @@ jobs:
         id: checkout
         uses: actions/checkout@v4
 
-      - name: Use Node.js 18.x
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18.x
-      
-      - name: Install Dependencies
-        run: npm install
+      - name: Process Pull Request
+        id: process-pr
+        run: |
+          LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
+          echo "::debug::Labels: $LABELS"
 
-      - name: Bump version
-        id: version-bump
-        uses: 4Source/version-control-action@v1
-        with: 
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          owner: ${{ github.repository_owner }}
-          repository:  ${{ github.event.repository.name }}
-          pr_number: ${{ github.event.number }}
-          tag_prefix: ''
-          dry_run: true
+          if echo "$LABELS" | grep -q 'major'; then
+            RELEASE_TYPE_TAG="major"
+          elif echo "$LABELS" | grep -q 'minor'; then
+            RELEASE_TYPE_TAG="minor"
+          elif echo "$LABELS" | grep -q 'patch'; then
+            RELEASE_TYPE_TAG="patch"
+          else
+            echo "::error::No tag found matching a release type."
+            exit 1
+          fi
+
+          echo "Release tag: $RELEASE_TYPE_TAG"
+          echo "release_type=$RELEASE_TYPE_TAG" >> $GITHUB_OUTPUT
 
       - name: Configure git
         run: |
-          git config --global user.name "4Source"
-          git config --global user.email "38220764+4Source@users.noreply.github.com."
-
-      - name: Change version in files
-        run: | 
-          npm run version -- --new_version=${{ steps.version-bump.outputs.new_version }}
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
       
-      - name: Commit and push changes
+      - name: Create or Update release type tag
         run: |
-          git commit -a -m "Apply version ${{ steps.version-bump.outputs.new_version }}"
-          git push -f 
-      
-      - name: Push version tag
-        run: |
-          git tag -a ${{ steps.version-bump.outputs.new_version }} -m "${{ steps.version-bump.outputs.new_version }}"
-          git push -f origin ${{ steps.version-bump.outputs.new_version }}
-
-      - name: Build plugin
-        run: npm run build
-  
-      - name: Create release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          FILES="main.js manifest.json"
-          if [ -f styles.css ]; then
-            FILES="$FILES styles.css"
-          fi
-          gh release create "${{ steps.version-bump.outputs.new_version }}" \
-            --title "${{ steps.version-bump.outputs.new_version }}" \
-            --draft $FILES
+          git tag -fa ${{ steps.process-pr.outputs.release_type }} -m "${{ steps.process-pr.outputs.release_type }}"
+          git push origin -f ${{ steps.process-pr.outputs.release_type }}
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,138 +1,35 @@
-name: Continuous Integration
+name: Release new plugin version
 
-on: 
-  pull_request:
-    types: 
-      - opened
-      - synchronize
-      - reopened
-      - labeled
-      - unlabeled
-    paths: 
-      - 'src/**'
-      - 'test/**'
-  push: 
-    paths: 
-      - 'src/**'
-      - 'test/**'
-    branches: 
-       - master  
+on:
+  workflow_dispatch:
+    inputs:
+      selected_release_type:
+        description: "Choose version update type"
+        required: true
+        default: "auto"
+        type: choice
+        options:
+          - auto
+          - patch
+          - minor
+          - major
+      force_release:
+        description: "Forces a release even without changes (not auto)"
+        type: boolean
+        default: false
+
+  schedule:
+    # Schedule automatic release every Wednesday
+    # - cron: "0 0 * * 3"
 
 jobs:
-  test:
-    strategy:
-      matrix:
-        os: [ ubuntu-latest, windows-latest, macos-latest ]
-
-    name: Run unit tests
-    runs-on: ${{ matrix.os }}
-
-    steps:
-      - name: Checkout repository 
-        uses: actions/checkout@v4
-
-      - name: Use Node.js "18.x"
-        uses: actions/setup-node@v4
-        with:
-          node-version: "18.x"
-      
-      - name: Install Dependencies
-        run: npm install
-
-      - name: Run Tests
-        run: npm run test
-
-  lint:
-    name: Run linter
+  release:
     runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout repository 
-        uses: actions/checkout@v4
-
-      - name: Use Node.js 18.x
-        uses: actions/setup-node@v4
-        with:
-          node-version: "18.x"
-      
-      - name: Install Dependencies
-        run: npm install
-      
-      - name: Run linter
-        run: npm run lint
-
-  build: 
-    name: Build Plugin
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout repository 
-        uses: actions/checkout@v4
-
-      - name: Use Node.js 18.x
-        uses: actions/setup-node@v4
-        with:
-          node-version: "18.x"
-      
-      - name: Install Dependencies
-        run: npm install
-
-      - name: Run Build
-        run: npm run build
-  
-  audit: 
-    name: Security Audit
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout repository 
-        uses: actions/checkout@v4
-
-      - name: Use Node.js 18.x
-        uses: actions/setup-node@v4
-        with:
-          node-version: "18.x"
-      
-      - name: Install Dependencies
-        run: npm install
-
-      - name: Audit for vulnerabilities
-        run: npm audit --audit-level=moderate
-
-  version:
-    name: Version Bump 
-    runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request'
-
-    steps:
-      - name: Checkout
-        id: checkout
-        uses: actions/checkout@v4
-      - name: Bump version
-        uses: 4Source/version-control-action@v1
-        with: 
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          owner: ${{ github.repository_owner }}
-          repository:  ${{ github.event.repository.name }}
-          pr_number: ${{ github.event.number }}
-          tag_prefix: ''
-          dry_run: true
-
-  beta-release:
-    name: Beta releases for pull requests
-    runs-on: ubuntu-latest
-    needs: 
-      - test 
-      - build 
-      - version
-    # TODO: Beta releases are currently disabled
-    if: github.event_name == 'pull_request' && false
-
-    permissions: 
+    permissions:
       pull-requests: write
       contents: write
 
-    steps: 
+    steps:
       - name: Checkout
         id: checkout
         # TODO: Have to use this commit because fetch-tags is not working in main till this is merged to main
@@ -145,7 +42,7 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 18.x
-      
+
       - name: Check changes since last release
         id: changes
         run: |
@@ -161,11 +58,33 @@ jobs:
           else
             echo "Last tag: $LAST_VERSION_TAG"
             if git diff --quiet "$LAST_VERSION_TAG"..HEAD -- src/; then
-              echo "No changes in /src since last release."
-              echo "skip=true" >> $GITHUB_OUTPUT
-              exit 0
+              if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+                echo "::warning::No changes in /src since last release."
+                FORCE_RELEASE="${{ github.event.inputs.force_release || false }}"
+                if $FORCE_RELEASE && [ "${{ inputs.selected_release_type }}" != "auto" ]; then
+                  echo "::warning::Forced release."
+                elif $FORCE_RELEASE && [ "${{ inputs.selected_release_type }}" == "auto" ]; then
+                  echo "::error::Forces is not possible with release type auto."
+                  exit 1
+                else 
+                  exit 1
+                fi
+              elif [ "${{ github.event_name }}" == "schedule" ]; then
+                echo "No changes in /src since last release."
+                echo "skip=true" >> $GITHUB_OUTPUT
+                exit 0
+              fi
             else
               echo "::debug::Changes detected in /src since last release."
+            fi
+          fi
+
+          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+            echo "Requested release type: ${{ inputs.selected_release_type }}"
+
+            if [ "${{ inputs.selected_release_type }}" != "auto" ]; then
+              echo "release_type=${{ inputs.selected_release_type }}" >> $GITHUB_OUTPUT
+              exit 0
             fi
           fi
 
@@ -183,8 +102,7 @@ jobs:
 
           echo "Release tag: $RELEASE_TYPE_TAG"
           echo "release_type=$RELEASE_TYPE_TAG" >> $GITHUB_OUTPUT
-                    
-      
+
       - name: Install Dependencies
         if: ${{ steps.changes.outputs.skip == 'false' }}
         run: npm install
@@ -193,14 +111,13 @@ jobs:
         if: ${{ steps.changes.outputs.skip == 'false' }}
         id: version-bump
         uses: 4Source/version-control-action@v1
-        with: 
+        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           owner: ${{ github.repository_owner }}
-          repository:  ${{ github.event.repository.name }}
+          repository: ${{ github.event.repository.name }}
           version_increase: ${{ steps.changes.outputs.release_type }}
-          tag_prefix: ''
+          tag_prefix: ""
           dry_run: true
-          # TODO: Is beta + beta string 
 
       - name: Configure git
         if: ${{ steps.changes.outputs.skip == 'false' }}
@@ -210,16 +127,16 @@ jobs:
 
       - name: Change version in files
         if: ${{ steps.changes.outputs.skip == 'false' }}
-        run: | 
+        run: |
           npm run version -- --new_version=${{ steps.version-bump.outputs.new_version }}
           git add manifest.json versions.json package.json
-      
+
       - name: Commit and push changes
         if: ${{ steps.changes.outputs.skip == 'false' }}
         run: |
           git commit -a -m "Apply version ${{ steps.version-bump.outputs.new_version }}"
           git push
-        
+
       - name: Push version tag
         if: ${{ steps.changes.outputs.skip == 'false' }}
         run: |
@@ -258,8 +175,9 @@ jobs:
             --title "${{ steps.version-bump.outputs.new_version }}" \
             --generate-notes \
             $FILES
-      
+
       - name: Remove release type tags
+        if: ${{ steps.changes.outputs.skip == 'false'}}
         run: |
           FAILED=0
 
